### ISSUE TITLE
Support for v3

### ISSUE THREAD

**Issue by CodeSkills** [bileto/omnipay-gopay#11]
Hi there, 

are you going to support also a v2 version of omnipay? Or are you open for PRs?

Thanks!

**Comment by jspetrak** [comment]
Hey @CodeSkills the 0.6.6 release is working with OmniPay v2. If you will miss any features in that, we could think of concurrent v2/v3 releases.

**Comment by CodeSkills** [comment]
Thanks for fast replay. We are currently thinking of moving to omnipay v3 so that's why I'm asking.

Ok, when we get to the point of integrating GoPay with v3 I will let you know and will try to make a v3 support.

**Comment by jspetrak** [comment]
@CodeSkills I do not understand. 0.6.6 is the latest written against v2. 0.7.0 and 0.8.0 support v3. If there is anything missing, please let us know or PR.
